# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hammer < Formula
  desc ""
  homepage ""
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://o.xdb.be/hammer/release/v0.0.9/hammer_Darwin_x86_64.tar.gz"
      sha256 "3fe290b66d8ec001ec9512057d2fc5d46f8b07a7f9eff64e7fa3565732d449eb"

      def install
        bin.install "hammer"
      end
    end
    if Hardware::CPU.arm?
      url "https://o.xdb.be/hammer/release/v0.0.9/hammer_Darwin_arm64.tar.gz"
      sha256 "da1e64f6ce83a8bb551ff9e5849361d34a7f582c4f2993c15d9b572684b63e8f"

      def install
        bin.install "hammer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://o.xdb.be/hammer/release/v0.0.9/hammer_Linux_x86_64.tar.gz"
      sha256 "fbdd11816af63b92dfa0dfb6e29ca8ea14f6cd50fae57ef346b5d662187811e3"
      def install
        bin.install "hammer"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://o.xdb.be/hammer/release/v0.0.9/hammer_Linux_arm64.tar.gz"
      sha256 "4966852921256318b6e8f5a1ea18840e39622f78c98cee3023ffd022026331f6"
      def install
        bin.install "hammer"
      end
    end
  end

  test do
    system "#{bin}/hammer version"
  end
end
