# This file was generated by GoReleaser. DO NOT EDIT.
cask "hammer" do
  name "hammer"
  desc ""
  homepage ""
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hammer"

  on_macos do
    on_intel do
      url "https://o.xdb.be/hammer/release/v#{version}/hammer_Darwin_x86_64.tar.gz"
      sha256 "1a0b5c187d94e9d0eed690810e23ed0da15c1d075600fb475b8658f02e623a33"
    end
    on_arm do
      url "https://o.xdb.be/hammer/release/v#{version}/hammer_Darwin_arm64.tar.gz"
      sha256 "c7dc6f5c4220af9ff176be9c86e75c99efcaf88964e7971d9f328382328169a0"
    end
  end

  on_linux do
    on_intel do
      url "https://o.xdb.be/hammer/release/v#{version}/hammer_Linux_x86_64.tar.gz"
      sha256 "2d44c32c22d22a933df2ec34de4c9dd18203c80948cabe68eb2be6b498791e25"
    end
    on_arm do
      url "https://o.xdb.be/hammer/release/v#{version}/hammer_Linux_arm64.tar.gz"
      sha256 "fdb1fcc169ac54b4b97f37b273d47fa8be1bf70061facc1fdba7c6c61dfe3ddb"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hammer"]
    end
  end

  # No zap stanza required
end
