# This file was generated by GoReleaser. DO NOT EDIT.
cask "hammer" do
  name "hammer"
  desc ""
  homepage ""
  version "0.2.0-alpha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hammer"

  on_macos do
    on_intel do
      url "https://o.xdb.be/hammer/release/v#{version}/hammer_Darwin_x86_64.tar.gz"
      sha256 "667eca5b888201319b77fa3b38a064529684f66c8dfaa497b27be0db600c6aad"
    end
    on_arm do
      url "https://o.xdb.be/hammer/release/v#{version}/hammer_Darwin_arm64.tar.gz"
      sha256 "d137e4e8d9778d8d4dd8fcc95075a7f68cc6fd7757f2f5b5420eeb2c64f95d04"
    end
  end

  on_linux do
    on_intel do
      url "https://o.xdb.be/hammer/release/v#{version}/hammer_Linux_x86_64.tar.gz"
      sha256 "2242262e96e6891d0af3240e879fe1c3d5e4b3bbd39786bf31d997459c723cfd"
    end
    on_arm do
      url "https://o.xdb.be/hammer/release/v#{version}/hammer_Linux_arm64.tar.gz"
      sha256 "d2857d9f80f4142fe3b70ae4bf014354b5d6cc47cb56533c09f83ad57a574c15"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hammer"]
    end
  end

  # No zap stanza required
end
