# This file was generated by GoReleaser. DO NOT EDIT.
cask "hammer" do
  name "hammer"
  desc ""
  homepage ""
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hammer"

  on_macos do
    on_intel do
      url "https://o.xdb.be/hammer/release/v#{version}/hammer_Darwin_x86_64.tar.gz"
      sha256 "8fdbe869b649d1a64f4047279a2332faf1bede9758e881066e6c468ed80a263b"
    end
    on_arm do
      url "https://o.xdb.be/hammer/release/v#{version}/hammer_Darwin_arm64.tar.gz"
      sha256 "bdd629a02afc0608a01f78f50b3224734e428ea408050f997d7e562f2e8c9959"
    end
  end

  on_linux do
    on_intel do
      url "https://o.xdb.be/hammer/release/v#{version}/hammer_Linux_x86_64.tar.gz"
      sha256 "f7f015b3cfcc6c9a63d645d903e28475c1e5a05dac5db3a233be683a61ba0b77"
    end
    on_arm do
      url "https://o.xdb.be/hammer/release/v#{version}/hammer_Linux_arm64.tar.gz"
      sha256 "a95b01127220b78477df9c7ac9213ddb2376cc399a3adb471d53af60471e55db"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hammer"]
    end
  end

  # No zap stanza required
end
